export const C = {
  bg: "#f0f2f5",
  surface: "#ffffff",
  surface2: "#f8f9fa",
  border: "rgba(0,0,0,0.08)",
  green: "#0a8a5c",
  blue: "#1a6eb5",
  red: "#c0392b",
  muted: "rgba(0,0,0,0.45)",
  dim: "rgba(0,0,0,0.25)",
};

export const s = {
  page: { minHeight:"100vh", background:C.bg, color:"#1a1a2e", fontFamily:"'IBM Plex Mono',monospace" },
  header: { borderBottom:`1px solid ${C.border}`, padding:"16px 24px", display:"flex", alignItems:"center", justifyContent:"space-between", background:"#ffffff", position:"sticky", top:0, zIndex:40, boxShadow:"0 1px 8px rgba(0,0,0,0.06)" },
  logo: { fontFamily:"'Syne',sans-serif", fontSize:22, fontWeight:900, letterSpacing:-0.5, color:"#1a1a2e" },
  badge: { fontSize:11, color:C.muted, display:"flex", alignItems:"center", gap:6 },
  dot: { width:7, height:7, borderRadius:"50%", background:C.green, animation:"pulse 2s infinite" },
  main: { maxWidth:1100, margin:"0 auto", padding:"32px 64px", display:"flex", flexDirection:"column", gap:20, width:"100%", alignItems:"stretch" },
  card: { background:C.surface, border:`1px solid ${C.border}`, borderRadius:16, padding:24, boxShadow:"0 2px 12px rgba(0,0,0,0.06)" },
  label: { fontSize:10, letterSpacing:"0.25em", textTransform:"uppercase", color:C.muted, display:"block", marginBottom:8 },
  input: { width:"100%", background:"#f8f9fa", border:`1px solid ${C.border}`, borderRadius:12, padding:"12px 16px", fontFamily:"'IBM Plex Mono',monospace", fontSize:14, color:"#1a1a2e", outline:"none", boxSizing:"border-box" },
  row: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:16 },
  algoRow: { display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 },
  algoBtn: (active, color) => ({
    padding:"14px 12px", borderRadius:14,
    border:`2px solid ${active?color:"rgba(0,0,0,0.1)"}`,
    background: active?`${color}15`:"#f8f9fa",
    color: active?color:"rgba(0,0,0,0.4)", cursor:"pointer", textAlign:"center",
    transition:"all 0.2s", fontFamily:"'IBM Plex Mono',monospace",
  }),
  paramBox: { background:"#f8f9fa", borderRadius:12, padding:"12px 14px", border:`1px solid ${C.border}` },
  paramRow: { display:"flex", alignItems:"center", gap:8 },
  paramBtn: { width:28, height:28, borderRadius:8, background:"#fff", border:`1px solid rgba(0,0,0,0.12)`, color:"#333", cursor:"pointer", fontSize:16, display:"flex", alignItems:"center", justifyContent:"center" },
  runBtn: (disabled) => ({
    padding:"13px 32px", borderRadius:12,
    background: disabled?"rgba(0,0,0,0.08)":C.green,
    color: disabled?"rgba(0,0,0,0.3)":"#fff",
    border:"none", cursor:disabled?"not-allowed":"pointer",
    fontFamily:"'IBM Plex Mono',monospace", fontWeight:700,
    fontSize:13, letterSpacing:"0.15em", textTransform:"uppercase",
    transition:"all 0.2s",
    boxShadow: disabled?"none":`0 4px 20px rgba(10,138,92,0.3)`,
  }),
  toggle: (on) => ({ width:40, height:22, borderRadius:11, background:on?C.green:"rgba(0,0,0,0.15)", position:"relative", cursor:"pointer", transition:"all 0.2s", border:"none", padding:0 }),
  toggleDot: (on) => ({ width:16, height:16, borderRadius:"50%", background:"#fff", position:"absolute", top:3, left:on?21:3, transition:"left 0.2s" }),
  cell: (isPath, val, revealed) => ({
    width:42, height:42, display:"flex", alignItems:"center", justifyContent:"center",
    fontSize:12, fontFamily:"'IBM Plex Mono',monospace",
    border:`1px solid rgba(0,0,0,0.07)`, borderRadius:6,
    background: !revealed?"#f0f2f5": isPath?"rgba(10,138,92,0.12)": val>0?"#daeeff": val<0?"#ffe8e8":"#f8f9fa",
    color: !revealed?"transparent": isPath?C.green: val>0?"#2980b9": val<0?"#e74c3c":"rgba(0,0,0,0.4)",
    fontWeight: isPath?700:400,
    boxShadow: isPath&&revealed?`0 0 8px rgba(10,138,92,0.25)`:"none",
    transition:"all 0.15s",
  }),
  headerCell: (color) => ({ width:42, height:42, display:"flex", alignItems:"center", justifyContent:"center", fontSize:14, fontWeight:700, color, fontFamily:"'IBM Plex Mono',monospace" }),
};